### ISSUE TITLE
Unable to dismiss calendar

### ISSUE THREAD

**Issue by airblade** [airblade/stimulus-datepicker#14]
A user reported that they were unable to dismiss the calendar.

Their steps to reproduce:

1. Click the calendar icon to open the calendar.
2. Click on another date.

Expected: the calendar disappears and the text input changes to show the clicked date.
Actual: the text input changes but the calendar does not disappear.  Neither clicking the calendar icon nor clicking elsewhere on the page has any effect.  At this point pressing F12 does not open the developer console.  The JavaScript console does not show any errors.

Firefox 105.0 (64-bit) on Ubuntu 18.04.

**Comment by airblade** [comment]
I cannot reproduce this on macOS with Firefox, Chrome, or Safari.  My Firefox is 106.0.1 (64-bit).

**Comment by airblade** [comment]
Maybe related? https://bugzilla.mozilla.org/show_bug.cgi?id=1573830

But F12 thing sounds like an infinite loop blocking the browser.

**Comment by airblade** [comment]
There is one infinite loop in the code:

https://github.com/airblade/stimulus-datepicker/blob/b672a0da67f28520cd1fc7a3375f44632122a595/src/datepicker.js#L470-L495

The code breaks out of it on line 474.

**Comment by YANOUSHek** [comment]
I just encountered this "bug" and this has to do with animations. Currently the code in the controller relies on the fact that the animation to close the calendar has to finish before the calendar is removed. If anyone (like me) overrode the animation to `none` or someone has reduced motion in their browser the calendar will not close.

**Comment by YANOUSHek** [comment]
Thank you. Works like a charm. Now if we could also fix #28 I would be super happy :D
