### ISSUE TITLE
Dispatch change event only when dateValue has changed

### ISSUE THREAD

**Issue by Yasser** [airblade/stimulus-datepicker#21]
Currently, Event('change') is being dispatched by selectDate after setting dateValue. However, dateValueChanged (a Stimulus callback) sets the actual input value. This means that the 'change' event is being triggered before the input value has actually changed, which may be unexpected for those who have registered eventListener(s) on the input element.

Does it make sense to move the dispatch to dateValueChanged?

**Comment by airblade** [comment]
That makes sense.

Please could you try 49ed3e6 and let me know if it solves your problem?  If so, I'll make a new release.

**Comment by Yasser** [comment]
Thank you, Andy. Confirmed, [49ed3e6](https://github.com/airblade/stimulus-datepicker/commit/49ed3e6c9e57fab17caf8ab5ae921b4334bfdf00) works as expected.

**Comment by airblade** [comment]
OK, thanks.  It's in v1.0.4.
